use Transporte_Bonilla
GO
INSERT [dbo].[Acceso] ([Codigo_Acceso], [Tipo_Acceso], [Descripcion_Acceso]) VALUES (1, N'Alto', N'Acceso Completo')
INSERT [dbo].[Acceso] ([Codigo_Acceso], [Tipo_Acceso], [Descripcion_Acceso]) VALUES (2, N'Medio', N'Acceso de consultor')
INSERT [dbo].[Acceso] ([Codigo_Acceso], [Tipo_Acceso], [Descripcion_Acceso]) VALUES (3, N'Bajo', N'Acceso Superficial')
INSERT [dbo].[Categoria] ([Codigo_Categoria], [Nombre_Categoria]) VALUES (N'CT', N'Contrato')
INSERT [dbo].[Categoria] ([Codigo_Categoria], [Nombre_Categoria]) VALUES (N'DC', N'Documentos')
INSERT [dbo].[Categoria] ([Codigo_Categoria], [Nombre_Categoria]) VALUES (N'EP', N'Empleado')
INSERT [dbo].[Categoria] ([Codigo_Categoria], [Nombre_Categoria]) VALUES (N'EV', N'Eventos')
INSERT [dbo].[Categoria] ([Codigo_Categoria], [Nombre_Categoria]) VALUES (N'MT', N'Mantenimientos')
INSERT [dbo].[Categoria] ([Codigo_Categoria], [Nombre_Categoria]) VALUES (N'PG', N'Pagos')
INSERT [dbo].[Categoria] ([Codigo_Categoria], [Nombre_Categoria]) VALUES (N'RT', N'Rutas')
INSERT [dbo].[Categoria] ([Codigo_Categoria], [Nombre_Categoria]) VALUES (N'VE', N'Vehiculos')
INSERT [dbo].[Cliente] ([Codigo_Cliente], [Nombre_Cliente], [Direccion_Cliente], [Telefono_Cliente], [Correo_Cliente]) VALUES (N'0801199000001', N'Berta Romero', N'Col. Hato del Medio, Sector 7', 96273132, N'maro@yahoo.com')
INSERT [dbo].[Cliente] ([Codigo_Cliente], [Nombre_Cliente], [Direccion_Cliente], [Telefono_Cliente], [Correo_Cliente]) VALUES (N'0801199802725', N'Eduardo Salgado', N'Nowhere', 33967131, N'esalgado@dowalschool.net')
INSERT [dbo].[Cliente] ([Codigo_Cliente], [Nombre_Cliente], [Direccion_Cliente], [Telefono_Cliente], [Correo_Cliente]) VALUES (N'0802199900011', N'Juanita Marina', N'Col. Bella Oriente, Bloque J, Casa 4513', 22555684, N'jmarina@hotmail.com')
INSERT [dbo].[Contratos] ([Codigo_Contrato], [Cliente_Contrato], [Tipo_Contrato], [Fecha_Inicio_Contrato], [Monto_Contrato], [Fecha_Vencimiento], [Estado_Contrato], [Cod_Documento]) VALUES (N'JESRTransporte', N'0801199802725', 1, CAST(N'1998-01-26' AS Date), 160000.0000, CAST(N'3020-01-01' AS Date), N'001', N'CTJesr')
INSERT [dbo].[Contratos] ([Codigo_Contrato], [Cliente_Contrato], [Tipo_Contrato], [Fecha_Inicio_Contrato], [Monto_Contrato], [Fecha_Vencimiento], [Estado_Contrato], [Cod_Documento]) VALUES (N'TransporteUNICAH', N'0801199000001', 3, CAST(N'2019-06-06' AS Date), 4500.0000, CAST(N'2019-06-07' AS Date), N'002', N'CTUnicah')
INSERT [dbo].[Documentos] ([Codigo_Documento], [Nombre_Documento]) VALUES (N'AP', N'Ante. Penales')
INSERT [dbo].[Documentos] ([Codigo_Documento], [Nombre_Documento]) VALUES (N'APl', N'Ante. Policiales')
INSERT [dbo].[Documentos] ([Codigo_Documento], [Nombre_Documento]) VALUES (N'CCP', N'Carta Compromiso')
INSERT [dbo].[Documentos] ([Codigo_Documento], [Nombre_Documento]) VALUES (N'CTJesr', N'Contrato JESR')
INSERT [dbo].[Documentos] ([Codigo_Documento], [Nombre_Documento]) VALUES (N'CTr', N'Contrato')
INSERT [dbo].[Documentos] ([Codigo_Documento], [Nombre_Documento]) VALUES (N'CTUnicah', N'Contrato Unicah')
INSERT [dbo].[Documentos] ([Codigo_Documento], [Nombre_Documento]) VALUES (N'CV', N'Curriculum Vitae')
INSERT [dbo].[Documentos] ([Codigo_Documento], [Nombre_Documento]) VALUES (N'ID', N'Identidad')
INSERT [dbo].[Documentos] ([Codigo_Documento], [Nombre_Documento]) VALUES (N'IHSS', N'Carnet Seguro')
INSERT [dbo].[Documentos_Relacion] ([Codigo_Documento], [Identidad_Empleado], [Estado_Documento], [Documento], [Fecha_Emision], [Fecha_Vencimiento]) VALUES (N'AP', N'1', N'102', N'/documentos/AP.jpg', CAST(N'2019-01-26' AS Date), CAST(N'2019-01-29' AS Date))
INSERT [dbo].[Documentos_Relacion] ([Codigo_Documento], [Identidad_Empleado], [Estado_Documento], [Documento], [Fecha_Emision], [Fecha_Vencimiento]) VALUES (N'APL', N'1', N'101', N'/documentos/APL.jpg', CAST(N'2019-01-26' AS Date), CAST(N'2020-01-29' AS Date))
INSERT [dbo].[Documentos_Relacion] ([Codigo_Documento], [Identidad_Empleado], [Estado_Documento], [Documento], [Fecha_Emision], [Fecha_Vencimiento]) VALUES (N'CCP', N'1', N'101', N'/documentos/cartacompromiso.jpg', CAST(N'2019-02-28' AS Date), CAST(N'2020-06-01' AS Date))
INSERT [dbo].[Empleado] ([Identidad_Empleado], [Nombre_Empleado], [Fecha_Nacimiento], [Genero], [Telefono], [Correo], [Direccion], [Puesto_Empleado], [Salario]) VALUES (N'1', N'Juanita Perez', CAST(N'1998-01-26' AS Date), N'Femenino', 12345678, N'jperez@gmail.com', N'Colonia Robles Este', 5, 15000.0000)
INSERT [dbo].[Empleado] ([Identidad_Empleado], [Nombre_Empleado], [Fecha_Nacimiento], [Genero], [Telefono], [Correo], [Direccion], [Puesto_Empleado], [Salario]) VALUES (N'2', N'Jorgito Jaimitio', CAST(N'1990-01-01' AS Date), N'Masculino', 13123134, N'jjaimez@hotmail.com', N'Colonia Linda Vista', 2, 25000.0000)
INSERT [dbo].[Empleado] ([Identidad_Empleado], [Nombre_Empleado], [Fecha_Nacimiento], [Genero], [Telefono], [Correo], [Direccion], [Puesto_Empleado], [Salario]) VALUES (N'3', N'Erickcito Martinez', CAST(N'1996-10-28' AS Date), N'Masculino', 13124124, N'pineapple@yahoo.com', N'Colonia Comayagua', 4, 24999.9900)
INSERT [dbo].[Empleado] ([Identidad_Empleado], [Nombre_Empleado], [Fecha_Nacimiento], [Genero], [Telefono], [Correo], [Direccion], [Puesto_Empleado], [Salario]) VALUES (N'4', N'Lidia Jimenez', CAST(N'1999-02-14' AS Date), N'Femenino', 14122141, N'ljimenez@hi5.net', N'Colonia AmericoVespusio', 1, 26000.0000)
INSERT [dbo].[Empleado] ([Identidad_Empleado], [Nombre_Empleado], [Fecha_Nacimiento], [Genero], [Telefono], [Correo], [Direccion], [Puesto_Empleado], [Salario]) VALUES (N'5', N'Stephen Maximus', CAST(N'1976-01-15' AS Date), N'Masculino', 12142141, N'sstephen@yahoo.com', N'Colonia Trapss', 3, 24000.0000)
INSERT [dbo].[Empleado] ([Identidad_Empleado], [Nombre_Empleado], [Fecha_Nacimiento], [Genero], [Telefono], [Correo], [Direccion], [Puesto_Empleado], [Salario]) VALUES (N'6', N'Anthony Nintendo', CAST(N'1986-07-23' AS Date), N'Masculino', 41224213, N'NintendoMaria@nintendo.net', N'Colonia Mario Bros', 10, 23213.2100)
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'001', N'CT', N'Vigente', N'Contrato Vigente')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'002', N'CT', N'No Vigente', N'Contrato No Vigente')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'003', N'CT', N'Sin Validar', N'Contrato sin Firma')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'101', N'DC', N'Vigente', N'Documento Vigente')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'102', N'DC', N'No Vigente', N'Documento Vencido')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'201', N'EP', N'Enfermo', N'Con Incapacidad')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'301', N'EV', N'Sin Retornar', N'El vehiculo no ha sido retornada aun')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'302', N'EV', N'Retornado', N'El vehiculo fue retornado')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'303', N'EV', N'Retornado con Atraso', N'El vehiculo se retorno fuera de la hora laboral')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'304', N'EV', N'Concluido', N'Evento Terminado')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'305', N'EV', N'En Proceso', N'Eventro en Proceso')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'401', N'MT', N'Sin Empezar', N'Aun no se ha empezado el mantenimiento')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'402', N'MT', N'En Proceso', N'El mantenimiento se esta llevando acabo')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'403', N'MT', N'Concluido', N'Se concluyo el mantenimiento correctamente')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'501', N'PG', N'Pagado', N'Se realizo el pago sin problemas')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'502', N'PG', N'Sin Pagar', N'Aun no se ha realizado el Pago')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'503', N'PG ', N'Moroso', N'Tiene deuda con la empresa')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'604', N'RT', N'Deshabilitada', N'Hay problema en la Ruta')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'605', N'RT', N'Segura', N'La ruta no presenta ningun problema')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'701', N'VE', N'En Mantenimiento', N'El vehiculo esta en mantenimiento')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'702', N'VE', N'Disponible', N'El vehiculo esta listo para rodar')
INSERT [dbo].[Estado] ([Codigo_Estado], [Codigo_Categoria], [Nombre_Estado], [Descripcion_Estado]) VALUES (N'703', N'VE', N'Da�ado', N'El vehiculo esta fuera de servicio')
INSERT [dbo].[Eventos] ([Cod_Evento], [Nombre_Evento], [Motivo_Evento], [Descripcion_Evento], [Inicio_Evento], [Conclusion_Evento], [Estado_Evento], [Responsable_Evento], [Vehiculo_Evento]) VALUES (N'ChoqueV001', N'Choque Vehiculo', N'Colision', N'Choque con Bolo', CAST(N'2019-05-30' AS Date), CAST(N'2019-06-30' AS Date), N'304', N'3', N'PAW4234')
INSERT [dbo].[Eventos] ([Cod_Evento], [Nombre_Evento], [Motivo_Evento], [Descripcion_Evento], [Inicio_Evento], [Conclusion_Evento], [Estado_Evento], [Responsable_Evento], [Vehiculo_Evento]) VALUES (N'PrestamoV001', N'Prestamo Vehiculo', N'Extravio Llaves', N'Llaves Perdidas', CAST(N'2019-01-26' AS Date), CAST(N'2019-01-30' AS Date), N'305', N'2', N'PAF5039')
INSERT [dbo].[Mantenimientos] ([Codigo_Mantenimiento], [Tipo_Mantenimiento], [Fecha_Mantenimiento], [Codigo_Vehiculo], [Costo_Mantenimiento], [Estado_Mantenimiento]) VALUES (1, 1, CAST(N'2019-01-27' AS Date), N'PAF5039', 1500.0000, N'402')
INSERT [dbo].[Mantenimientos] ([Codigo_Mantenimiento], [Tipo_Mantenimiento], [Fecha_Mantenimiento], [Codigo_Vehiculo], [Costo_Mantenimiento], [Estado_Mantenimiento]) VALUES (2, 5, CAST(N'2019-01-27' AS Date), N'PAW4234', 9000.0000, N'403')
INSERT [dbo].[Perfiles] ([Codigo_Perfil], [Nivel_Acceso], [Nombre_Perfil], [Descripcion_Perfil]) VALUES (1, 1, N'Administrador', N'Tiene acceso completo')
INSERT [dbo].[Perfiles] ([Codigo_Perfil], [Nivel_Acceso], [Nombre_Perfil], [Descripcion_Perfil]) VALUES (2, 2, N'Consultor', N'Puede hacer consultas')
INSERT [dbo].[Perfiles] ([Codigo_Perfil], [Nivel_Acceso], [Nombre_Perfil], [Descripcion_Perfil]) VALUES (3, 2, N'Digitalizador', N'Puede ingresar datos')
INSERT [dbo].[Perfiles] ([Codigo_Perfil], [Nivel_Acceso], [Nombre_Perfil], [Descripcion_Perfil]) VALUES (4, 2, N'Auditor', N'Puede modifcar datos')
INSERT [dbo].[Perfiles] ([Codigo_Perfil], [Nivel_Acceso], [Nombre_Perfil], [Descripcion_Perfil]) VALUES (5, 2, N'Empleado', N'Puede Ingresar, Modificar y Consultar')
INSERT [dbo].[Perfiles] ([Codigo_Perfil], [Nivel_Acceso], [Nombre_Perfil], [Descripcion_Perfil]) VALUES (6, 3, N'Invitado', N'Solo puede ver notificaciones')
INSERT [dbo].[Perfiles] ([Codigo_Perfil], [Nivel_Acceso], [Nombre_Perfil], [Descripcion_Perfil]) VALUES (7, 3, N'Pasante ', N'Invitado con usuario')
INSERT [dbo].[Puesto] ([Codigo_Puesto], [Nombre_Puesto], [Descripcion_Puesto]) VALUES (1, N'Asistente Tecnico', N'Trabaja con IT')
INSERT [dbo].[Puesto] ([Codigo_Puesto], [Nombre_Puesto], [Descripcion_Puesto]) VALUES (2, N'Gerente de IT', N'Jefe de IT')
INSERT [dbo].[Puesto] ([Codigo_Puesto], [Nombre_Puesto], [Descripcion_Puesto]) VALUES (3, N'Asistente de RRHH', N'Asiste al gerente de IT')
INSERT [dbo].[Puesto] ([Codigo_Puesto], [Nombre_Puesto], [Descripcion_Puesto]) VALUES (4, N'Gerente de RRHH', N'Jefe de RRHH')
INSERT [dbo].[Puesto] ([Codigo_Puesto], [Nombre_Puesto], [Descripcion_Puesto]) VALUES (5, N'Aseador', N'Asea las oficinas')
INSERT [dbo].[Puesto] ([Codigo_Puesto], [Nombre_Puesto], [Descripcion_Puesto]) VALUES (6, N'Guardias', N'Cuida las oficinas')
INSERT [dbo].[Puesto] ([Codigo_Puesto], [Nombre_Puesto], [Descripcion_Puesto]) VALUES (7, N'Portero', N'Abre las puertas')
INSERT [dbo].[Puesto] ([Codigo_Puesto], [Nombre_Puesto], [Descripcion_Puesto]) VALUES (8, N'Cajero', N'Empleado que cobra en caja')
INSERT [dbo].[Puesto] ([Codigo_Puesto], [Nombre_Puesto], [Descripcion_Puesto]) VALUES (9, N'Chofer', N'Maneja los vehiculos de la empresa')
INSERT [dbo].[Puesto] ([Codigo_Puesto], [Nombre_Puesto], [Descripcion_Puesto]) VALUES (10, N'Desarrollador', N'Desarrolla Cosas')
INSERT [dbo].[Recibos] ([Num_Recibo], [Numero_Cuota], [Codigo_Contrato], [Codigo_Documento], [Fecha_Recibo], [Monto], [Numero_CAI]) VALUES (1, 1, N'JESRtransporte', N'CTJesr', CAST(N'2018-01-26' AS Date), 16000.0000, N'001')
INSERT [dbo].[Recibos] ([Num_Recibo], [Numero_Cuota], [Codigo_Contrato], [Codigo_Documento], [Fecha_Recibo], [Monto], [Numero_CAI]) VALUES (2, 2, N'JESRtransporte', N'CTJesr', CAST(N'2018-02-26' AS Date), 16000.0000, N'001')
INSERT [dbo].[Recibos] ([Num_Recibo], [Numero_Cuota], [Codigo_Contrato], [Codigo_Documento], [Fecha_Recibo], [Monto], [Numero_CAI]) VALUES (3, 1, N'TransporteUnicah', N'CTUnicah', CAST(N'2019-01-01' AS Date), 1500.0000, N'021')
INSERT [dbo].[Rutas] ([Codigo_Ruta], [Nombre_Ruta], [Descripcion_Ruta], [Codigo_Contrato]) VALUES (N'JESREntrada', N'Entrada de Empleado', N'Recoger Empleados', N'JESRtransporte')
INSERT [dbo].[Rutas] ([Codigo_Ruta], [Nombre_Ruta], [Descripcion_Ruta], [Codigo_Contrato]) VALUES (N'JESRsalida', N'Salida de Empleado', N'Despacho Empleado', N'JESRtransporte')
INSERT [dbo].[Rutas] ([Codigo_Ruta], [Nombre_Ruta], [Descripcion_Ruta], [Codigo_Contrato]) VALUES (N'UNICAHPlazaM', N'Plaza Miraf. Mana', N'Transporte Ma�ana', N'TransporteUnicah')
INSERT [dbo].[Tipo_Mantenimientos] ([Codigo_Tipo_Mantenimiento], [Nombre_Mantenimiento], [Descripcion_Mantenimiento]) VALUES (1, N'Cambio Aceite', N'Cambio de aceite quemado')
INSERT [dbo].[Tipo_Mantenimientos] ([Codigo_Tipo_Mantenimiento], [Nombre_Mantenimiento], [Descripcion_Mantenimiento]) VALUES (2, N'Cambio de llantas', N'Cambio de llantas gastadas')
INSERT [dbo].[Tipo_Mantenimientos] ([Codigo_Tipo_Mantenimiento], [Nombre_Mantenimiento], [Descripcion_Mantenimiento]) VALUES (3, N'Cambio de asientos', N'Cambio de asientos maltratados')
INSERT [dbo].[Tipo_Mantenimientos] ([Codigo_Tipo_Mantenimiento], [Nombre_Mantenimiento], [Descripcion_Mantenimiento]) VALUES (4, N'Arreglos Electricos', N'Aparatos Electricos')
INSERT [dbo].[Tipo_Mantenimientos] ([Codigo_Tipo_Mantenimiento], [Nombre_Mantenimiento], [Descripcion_Mantenimiento]) VALUES (5, N'Pintura', N'Retoques de Pintura')
INSERT [dbo].[Tipo_Mantenimientos] ([Codigo_Tipo_Mantenimiento], [Nombre_Mantenimiento], [Descripcion_Mantenimiento]) VALUES (6, N'Suspension', N'Arreglar Suspension')
INSERT [dbo].[Tipo_Mantenimientos] ([Codigo_Tipo_Mantenimiento], [Nombre_Mantenimiento], [Descripcion_Mantenimiento]) VALUES (7, N'Transmision', N'Mantenimiento a Transmision')
INSERT [dbo].[Tipo_Mantenimientos] ([Codigo_Tipo_Mantenimiento], [Nombre_Mantenimiento], [Descripcion_Mantenimiento]) VALUES (8, N'Motor', N'Mantenimiento al motor del vehiculo')
INSERT [dbo].[TipoContrato] ([Cod_Contrato], [Tipo_Contrato], [Descripcion_Contrato]) VALUES (1, N'Permanente', N'Contrato Permanente Mensual')
INSERT [dbo].[TipoContrato] ([Cod_Contrato], [Tipo_Contrato], [Descripcion_Contrato]) VALUES (2, N'Temporal', N'Contrato por tiempo')
INSERT [dbo].[TipoContrato] ([Cod_Contrato], [Tipo_Contrato], [Descripcion_Contrato]) VALUES (3, N'Privado', N'Contrato por un viaje')
INSERT [dbo].[Usuarios] ([Codigo_Empleado], [Nombre_Usuario], [Contrasena_Usuario], [Perfil_Acceso]) VALUES (N'6', N'athompson', N'1', 1)
INSERT [dbo].[Usuarios] ([Codigo_Empleado], [Nombre_Usuario], [Contrasena_Usuario], [Perfil_Acceso]) VALUES (N'3', N'ebonilla', N'1', 1)
INSERT [dbo].[Usuarios] ([Codigo_Empleado], [Nombre_Usuario], [Contrasena_Usuario], [Perfil_Acceso]) VALUES (N'1', N'esalgado', N'berta66', 1)
INSERT [dbo].[Usuarios] ([Codigo_Empleado], [Nombre_Usuario], [Contrasena_Usuario], [Perfil_Acceso]) VALUES (N'2', N'jsalgado', N'1', 5)
INSERT [dbo].[Usuarios] ([Codigo_Empleado], [Nombre_Usuario], [Contrasena_Usuario], [Perfil_Acceso]) VALUES (N'4', N'lmejia', N'1', 1)
INSERT [dbo].[Usuarios] ([Codigo_Empleado], [Nombre_Usuario], [Contrasena_Usuario], [Perfil_Acceso]) VALUES (N'5', N'sduarte', N'1', 1)
INSERT [dbo].[Vehiculos] ([Codigo_Vehiculo], [Tipo_Vehiculo], [Anio_Vehiculo], [Marca_Vehiculo], [Modelo_Vehiculo], [Capacidad_Vehiculo], [Transmision_Vehiculo], [Combustible_Vehiculo], [Color_Vehiculo], [Anio_Adquisicion], [Estado_Vehiculo], [Emision_Permiso], [Vencimiento_Permiso], [Responsable_Vehiculo]) VALUES (N'PAF5039', N'Microbus', 1991, N'Toyota', N'Sorento', 20, N'Manual', N'Regular', N'Rojo', 2010, N'701', CAST(N'2015-01-26' AS Date), CAST(N'2020-01-26' AS Date), N'2')
INSERT [dbo].[Vehiculos] ([Codigo_Vehiculo], [Tipo_Vehiculo], [Anio_Vehiculo], [Marca_Vehiculo], [Modelo_Vehiculo], [Capacidad_Vehiculo], [Transmision_Vehiculo], [Combustible_Vehiculo], [Color_Vehiculo], [Anio_Adquisicion], [Estado_Vehiculo], [Emision_Permiso], [Vencimiento_Permiso], [Responsable_Vehiculo]) VALUES (N'PAW4234', N'Bus', 2010, N'Mazda', N'Corolla', 40, N'Automatico', N'Super', N'Amarillo', 2011, N'702', CAST(N'2012-01-01' AS Date), CAST(N'2032-01-01' AS Date), N'3')
INSERT [dbo].[Vehiculos_Rutas] ([Codigo_Ruta], [Codigo_Vehiculo], [Horario_Salida], [Horario_Entrada]) VALUES (N'JESRSalida', N'PAF5039', CAST(N'20:00:00' AS Time), CAST(N'21:45:00' AS Time))
INSERT [dbo].[Vehiculos_Rutas] ([Codigo_Ruta], [Codigo_Vehiculo], [Horario_Salida], [Horario_Entrada]) VALUES (N'JESREntrada', N'PAF5039', CAST(N'07:00:00' AS Time), CAST(N'08:30:00' AS Time))
INSERT [dbo].[Vehiculos_Rutas] ([Codigo_Ruta], [Codigo_Vehiculo], [Horario_Salida], [Horario_Entrada]) VALUES (N'UNICAHPlazaM', N'PAW4234', CAST(N'08:30:00' AS Time), CAST(N'09:30:00' AS Time))
INSERT [dbo].[Vehiculos_Rutas] ([Codigo_Ruta], [Codigo_Vehiculo], [Horario_Salida], [Horario_Entrada]) VALUES (N'UNICAHPlazaM', N'PAW4234', CAST(N'09:45:00' AS Time), CAST(N'10:30:00' AS Time))
INSERT [dbo].[Vehiculos_Rutas] ([Codigo_Ruta], [Codigo_Vehiculo], [Horario_Salida], [Horario_Entrada]) VALUES (N'UNICAHPlazaM', N'PAW4234', CAST(N'10:45:00' AS Time), CAST(N'11:30:00' AS Time))